### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by gleeke** [invictus-ir/Invictus-AWS#1]
```
         ❌ MACIE - No Configuration
         ❌ CLOUDTRAIL - No Configuration
Traceback (most recent call last):
  File "/home/admin/scripts/invictus-aws.py", line 1696, in <module>
    main()
  File "/home/admin/scripts/invictus-aws.py", line 1692, in main
    ir.execute_configuration()
  File "/home/admin/scripts/invictus-aws.py", line 1663, in execute_configuration
    self.c.execute(self.active_services)
  File "/home/admin/scripts/invictus-aws.py", line 465, in execute
    write_s3(self.bucket, CONFIGURATION_KEY, json.dumps(self.results, indent=4))
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by invictus-ir** [comment]
Need to do some testing to see if I can reproduce this.

**Comment by invictus-ir** [comment]
Issue resolved in latest version.
